# Lie Algebras calculation in Python

In [29]:
from scipy.spatial.transform import Rotation as R
import numpy as np

### 基本使用：创建旋转对象，叠加，作用

In [ ]:
# 旋转向量
rot_vec = [0,0,np.pi/2]
# 旋转矩阵
rot_matrix = np.array([[0,-1,0],[1,0,0],[0,0,1]])
# 四元数，默认为[x, y, z, w] 示例为绕z旋转90度
rot_quaternion = [0, 0, np.sin(np.pi/4), np.cos(np.pi/4)]

# 获得旋转的对象
r1 = R.from_rotvec(rot_vec)
r2 = R.from_matrix(rot_matrix)
r3 = R.from_quat(rot_quaternion)

# 多个旋转的叠加，实际效果为绕z转180度
r = r3 * r1

test_vec = (1,0,0)

# apply作用此旋转
after_rot = r.apply(test_vec)

print(np.round(after_rot,3))

[-1.  0.  0.]


### 求逆旋转

In [47]:
r_inv = r.inv()

print('Identical verification')
print((r_inv * r).as_matrix(),end='\n\n')

inversed = r_inv.apply(after_rot)
print(np.round(inversed,3))

Identical verification
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[1. 0. 0.]


### 不同旋转算符的转换

In [51]:
# 使用as_matrix()把其他表示改变为旋转矩阵
rot_matrix = r3.as_matrix()
print(f"rot_mat: \n{np.round(rot_matrix,2)}",end='\n\n')
# 使用as_quat()把其他表示改变为四元数
rot_quat = r1.as_quat()
print(f"rot_quat: \n{np.round(rot_quat,2)}",end='\n\n')
# 使用as_euler('zyx')转换为欧拉角
# 我们知道zyx欧拉角即为xyz固定角，于是此方法得到的为xyz固定角的结果
rot_euler = r1.as_euler('zyx', degrees=True)
# 使用大写字母时为外旋：绕世界坐标系即固定角
rot_euler = r1.as_euler('XYZ', degrees=True)
# 如下可见两种方式的计算结果是相同的
print(f"rot_euler ('zyx', degrees): \n{np.round(rot_euler, 1)}")
print(f"rot_euler ('XYZ', degrees): \n{np.round(rot_euler, 1)}")

rot_mat: 
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]

rot_quat: 
[0.   0.   0.71 0.71]

rot_euler ('zyx', degrees): 
[-0.  0. 90.]
rot_euler ('XYZ', degrees): 
[-0.  0. 90.]
